Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/coproid/main.ica.dev.nf --parameters-xml /Users/keng/nf-core/coproid/coproid.pipeline.updated.xml  --workflow-language nextflow --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_coproid --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/deepvariant/main.ica.dev.nf --parameters-xml /Users/keng/nf-core/deepvariant/deepvariant.pipeline.updated.xml --workflow-language nextflow --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_deepvariant --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/imcyto/main.ica.dev.nf --parameters-xml /Users/keng/nf-core/imcyto/imcyto.pipeline.updated.xml --nf-core-mode  --workflow-language nextflow --ica-project-name 'ken_debug' --pipeline-name test_pipeline_imcyto --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/neutronstar/main.ica.dev.nf --parameters-xml /Users/keng/nf-core/neutronstar/neutronstar.pipeline.updated.xml  --workflow-language nextflow --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_neutronstar --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/slamseq/main.ica.dev.nf --parameters-xml /Users/keng/nf-core/slamseq/slamseq.pipeline.updated.xml  --workflow-language nextflow --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_slamseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/atacseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/atacseq/atacseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_atacseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/cageseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/cageseq/cageseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_cageseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/chipseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/chipseq/chipseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_chipseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/clipseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/clipseq/clipseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_clipseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/diaproteomics/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/diaproteomics/diaproteomics.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_diaproteomics --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/dualrnaseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/dualrnaseq/dualrnaseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_dualrnaseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/eager/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/eager/eager.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_eager --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/hic/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/hic/hic.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_hic --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/hlatyping/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/hlatyping/hlatyping.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_hlatyping --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/metaboigniter/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/metaboigniter/metaboigniter.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_metaboigniter --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/methylseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/methylseq/methylseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_methylseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/pgdb/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/pgdb/pgdb.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_pgdb --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/proteomicslfq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/proteomicslfq/proteomicslfq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_proteomicslfq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/sarek/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/sarek/sarek.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_sarek --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/airrflow/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/airrflow/airrflow.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_airrflow --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/ampliseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/ampliseq/ampliseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_ampliseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/bacass/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/bacass/bacass.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_bacass --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/bactmap/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/bactmap/bactmap.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_bactmap --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/cutandrun/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/cutandrun/cutandrun.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_cutandrun --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/epitopeprediction/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/epitopeprediction/epitopeprediction.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_epitopeprediction --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/fetchngs/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/fetchngs/fetchngs.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_fetchngs --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/mag/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/mag/mag.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_mag --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/mhcquant/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/mhcquant/mhcquant.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_mhcquant --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/nanoseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/nanoseq/nanoseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_nanoseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/rnafusion/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/rnafusion/rnafusion.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_rnafusion --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/rnaseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/rnaseq/rnaseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_rnaseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/scrnaseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/scrnaseq/scrnaseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_scrnaseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/smrnaseq/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/smrnaseq/smrnaseq.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_smrnaseq --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com
Rscript nf-core.create_ica_pipeline.R --nextflow-script /Users/keng/nf-core/viralrecon/main.ica.dev.nf --workflow-language nextflow --parameters-xml /Users/keng/nf-core/viralrecon/viralrecon.pipeline.updated.xml --nf-core-mode --ica-project-name 'ken_debug' --pipeline-name test_pipeline_viralrecon --api-key-file /Users/keng/Downloads/ICAv2.isc_b.illumina-api-key.txt --simple-mode --base-ica-url ica.illumina.com