Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/coproid/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/deepvariant/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/imcyto/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/neutronstar/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/slamseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/atacseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/cageseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/chipseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/clipseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/diaproteomics/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/dualrnaseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/eager/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/hic/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/hlatyping/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/metaboigniter/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/methylseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/pgdb/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/proteomicslfq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/sarek/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/airrflow/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/ampliseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/bacass/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/bactmap/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/cutandrun/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/epitopeprediction/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/fetchngs/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/mag/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/mhcquant/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/nanoseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/rnafusion/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/rnaseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/scrnaseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/smrnaseq/main.ica.dev.nf
Rscript test_nextflow_script.R --nextflow-script /Users/keng/nf-core/viralrecon/main.ica.dev.nf
